apiVersion: skaffold/v2beta14
kind: Config
portForward:
  - resourceType: service
    resourceName: frontend-service
    port: 8080
    localPort: 8080
  - resourceType: service
    resourceName: backend-service
    port: 3000
    localPort: 3000
build:
  artifacts:
    - image: davidmc1/student-housing-frontend
      bazel:
        target: //frontend:image.tar
        args:
          ["--platforms=@build_bazel_rules_nodejs//toolchains/node:linux_amd64"]
      sync:
        manual:
          - src: "frontend/src/**"
            dest: .
    - image: davidmc1/student-housing-backend
      bazel:
        target: //backend:backend.tar
        args:
          ["--platforms=@io_bazel_rules_go//go/toolchain:linux_amd64"]
