# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: backend-deployment
# spec:
#   selector:
#     matchLabels:
#       name: backend-pod
#   replicas: 1
#   template:
#     metadata:
#       name: backend-pod
#       labels:
#         name: backend-pod
#     spec:
#       containers:
#         - name: backend
#           image: davidmc1/backend-image
#           ports:
#             - containerPort: 3000
#           resources:
#             limits:
#               cpu: "0.5"
#               memory: "128Mi"
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: backend-service
#   labels:
#     name: backend-service
# spec:
#   type: LoadBalancer
#   ports:
#     - port: 8080
#       targetPort: 3000
#   selector:
#     name: backend-pod
