apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      name: frontend-pod
  replicas: 1
  template:
    metadata:
      name: frontend-pod
      labels:
        name: frontend-pod
    spec:
      containers:
        - name: frontend
          image: davidmc1/student-housing-frontend
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    name: frontend-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: frontend-pod
