// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"student-housing-backend/ent"
)

type AbstractNode interface {
	IsAbstractNode()
}

type Connection interface {
	IsConnection()
}

type PaginationEdge interface {
	IsPaginationEdge()
}

type Address struct {
	StreetNumber string `json:"streetNumber"`
	StreetName   string `json:"streetName"`
	AddressLine2 string `json:"addressLine2"`
}

type NewUser struct {
	Name string `json:"name"`
}

type Property struct {
	Address      *Address    `json:"address"`
	BuildingName string      `json:"buildingName"`
	RoomType     []*RoomType `json:"roomType"`
	Owner        *ent.User   `json:"owner"`
}

type RoomType struct {
	NumBedrooms int `json:"numBedrooms"`
}
