// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in student-housing-backend/ent/runtime.go

const (
	Version = "(devel)" // Version of ent codegen.
)
